// Generated by CoffeeScript 1.7.1
(function() {
  Template.bottomNav.events({
    'click #deckButton': function(e) {
      return Deck.one().toggle();
    }
  });

}).call(this);

//# sourceMappingURL=bottomNav.map
